### ISSUE TITLE
Fetch order by redemption code doesn't work on iOS

### ISSUE THREAD

**Issue by david-netizen** [RadiusNetworks/flybuy-ios#11]
1. I've created order and got the new order as response like below.
<img width="384" alt="aaa" src="https://user-images.githubusercontent.com/63438918/124709559-3116ce80-df2e-11eb-9c9b-d5f76331e2cc.png">

2. I've tried to fetch order by using redemptioncode of created new order by using this method of SDK
   `FlyBuy.Core.orders.fetch(redemptionCode)`
   But I'm getting error: 
   [Error: We're having trouble finding this order. Contact the store for additional details about your order.]
   
   PS:  Fetch order by redemptioncode works well in android, but it doesn't work on iOS.

**Comment by botnerd** [comment]
Can you provide additional details for the SDK methods that were called and the order in which they were called? Please include any customer SDK calls as well.

**Comment by zeabdelkhalek** [comment]
@botnerd The steps to reproduce this issue is pretty simple:

1- First login with credentials.
2- Create a new order and save the redemption code
3- With that redemption code, try to call the function `fetchOrderByRedemptionCode` and you'll get this error
`We're having trouble finding this order. Contact the store for additional details about your order.`

Please note that this function works correctly on iOS and the issue is on Android only.

**Comment by botnerd** [comment]
`v2.1.2` of the SDK should resolve this issue for you. We will also have an update on the backend soon that will resolve it for older versions of the SDK. If the issue is not resolved, feel free to reopen the issue.
